import { ArrowRight, Bell, BookOpen, BriefcaseBusiness, CalendarDays, Check, ChevronRight, CircleHelp, Clock3, FileCheck2, MapPin, Search, ShieldCheck, Sparkles, TrendingUp, Users } from "lucide-react";

const API = process.env.API_URL ?? "http://localhost:4000";
type HomeJob = { id: string; slug: string; organization: string; postName: string; vacancy: number | null; salaryText: string | null; location: string[]; applicationEnd: string | null; verificationStatus: string; lastVerifiedAt: string | null; sourceKind: string };
type HomeUpdate = { id: string; title: string; type: string; sourceOrganization: string | null; job: { slug: string; organization: string } };
type HomeExam = { id: string; slug: string; name: string; organization: string; events: { type: string; date: string | null; title: string | null }[] };
async function getHomeContent() {
  try {
    const jobResponses = await Promise.all(
      Array.from({ length: 5 }, (_, index) =>
        fetch(`${API}/api/v1/jobs?page=${index + 1}&pageSize=50`, { next: { revalidate: 60 } })
      )
    );
    const [resultResponse, admitResponse, answerResponse, examsResponse] = await Promise.all([
      fetch(`${API}/api/v1/results`, { next: { revalidate: 60 } }),
      fetch(`${API}/api/v1/admit-cards`, { next: { revalidate: 60 } }),
      fetch(`${API}/api/v1/answer-keys`, { next: { revalidate: 60 } }),
      fetch(`${API}/api/v1/exams`, { next: { revalidate: 60 } }),
    ]);
    const jobs = (await Promise.all(jobResponses.map(async response => response.ok ? ((await response.json()).data as HomeJob[]) : []))).flat();
    const uniqueJobs = [...new Map(jobs.map(job => [job.id, job])).values()];
    const updates: HomeUpdate[] = [];
    for (const response of [resultResponse, admitResponse, answerResponse]) {
      if (response.ok) updates.push(...(await response.json()).data);
    }
    const exams: HomeExam[] = examsResponse.ok ? (await examsResponse.json()).data : [];
    return { jobs: uniqueJobs, updates, exams };
  } catch {
    return { jobs: [] as HomeJob[], updates: [] as HomeUpdate[], exams: [] as HomeExam[] };
  }
}
const categories = [{icon:"🏛️",name:"Central Government"},{icon:"🚆",name:"Railway Jobs"},{icon:"🛡️",name:"Defence Jobs"},{icon:"🏦",name:"Banking Jobs"},{icon:"📚",name:"Teaching Jobs"},{icon:"👮",name:"Police Jobs"},{icon:"🗺️",name:"State Government"},{icon:"⚖️",name:"State PSC"}];

function Brand(){return <a className="brand" href="#top"><span className="brand-mark">N</span><span>Naukri<span style={{color:"#087b69"}}>Mitra</span></span></a>}
function JobCard({job}:{job:HomeJob}){const verified=job.sourceKind==="OFFICIAL"&&job.verificationStatus==="VERIFIED"&&Boolean(job.lastVerifiedAt);return <article className="job-card"><div className="job-card-top"><div className="org"><div className="org-icon">{job.organization.slice(0,3).toUpperCase()}</div><div><b style={{fontSize:12}}>{job.organization}</b><small>{verified?"Official source verified":"Official source not yet verified"}</small></div></div><span className={verified?"pill":"status"}>{verified?"VERIFIED":"REVIEW SOURCE"}</span></div><h3>{job.postName}</h3><div className="job-meta"><span className="tag">{job.vacancy===null?"Vacancies not stated":`${job.vacancy} vacancies`}</span><span className="tag">{job.salaryText??"Salary in notification"}</span><span className="tag"><MapPin size={13} style={{display:"inline",verticalAlign:"middle"}}/> {job.location.join(", ")||"Refer to notification"}</span></div><div className="job-foot"><span><Clock3 size={13} style={{display:"inline",verticalAlign:"middle"}}/> {job.applicationEnd?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(job.applicationEnd)):"Closing date not stated"}</span><a className="link" href={`/jobs/${job.slug}`}>Review job <ChevronRight size={14} style={{display:"inline",verticalAlign:"middle"}}/></a></div></article>}

export default async function Home(){const {jobs,updates,exams}=await getHomeContent();return <main id="top"><header className="header"><div className="container header-in"><Brand/><nav className="nav"><a href="/jobs">Latest Jobs</a><a href="#updates">Results & Updates</a><a href="/calendar">Exam Calendar</a><a href="/eligibility">Eligibility</a></nav><div className="actions"><a href="/login" className="btn btn-light">Sign in</a><a href="/login" className="btn btn-primary">Create profile <ArrowRight size={15}/></a></div></div></header>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><Sparkles size={14}/> YOUR PERSONAL GOVERNMENT JOB ASSISTANT</span><h1>Find government jobs you're actually eligible for.</h1><p>Tell us about your qualifications and preferences. NaukriMitra helps you focus on opportunities that fit your profile, with official sources in view.</p><form action="/jobs" className="searchbox"><Search size={19} color="#64758b" style={{margin:"12px 0 12px 11px"}}/><input name="q" aria-label="Search jobs, exams, departments" placeholder="Search jobs, exams, departments..."/><button className="btn btn-primary">Search jobs</button></form><div className="hero-links"><a href="/dashboard" className="btn btn-primary">Find my jobs <ArrowRight size={15}/></a><a href="/dashboard" className="btn btn-light"><CircleHelp size={15}/> Check eligibility</a></div></div><aside className="hero-card"><div className="card-top"><div className="avatar">N</div><span className="pill">PROFILE MATCH</span></div><h3>Your next opportunity, made clearer.</h3><p>Build your profile to see relevant jobs and understand where you may need to check the official notice.</p><div className="match-row"><span>Qualification match</span><b><Check size={14} style={{display:"inline",verticalAlign:"middle"}}/> Ready to assess</b></div><div className="match-row"><span>Age & category</span><b>Profile needed</b></div><div className="match-row"><span>Official source</span><b><ShieldCheck size={14} style={{display:"inline",verticalAlign:"middle"}}/> Shown per job</b></div><div className="hero-card-foot"><Bell size={14} style={{display:"inline",verticalAlign:"middle"}}/> Set closing-date reminders on your dashboard</div></aside></div></section>
<div className="trust-strip"><div className="container trust-in"><span><ShieldCheck size={16} color="#087b69"/> Official sources clearly identified</span><span><Check size={16} color="#087b69"/> Eligibility explained, not guessed</span><span><Bell size={16} color="#087b69"/> Closing date reminders</span><span>Built for mobile, wherever you are</span></div></div>
<section className="section"><div className="container"><div className="metrics"><div className="metric"><div className="metric-icon"><BriefcaseBusiness size={19}/></div><div><strong>Job matches</strong><small>Personalized to your profile</small></div></div><div className="metric"><div className="metric-icon"><Clock3 size={19}/></div><div><strong>Closing soon</strong><small>Keep dates on your radar</small></div></div><div className="metric"><div className="metric-icon"><CalendarDays size={19}/></div><div><strong>Exam calendar</strong><small>Key milestones in one view</small></div></div><div className="metric"><div className="metric-icon"><FileCheck2 size={19}/></div><div><strong>Application tracker</strong><small>Stay on top of each step</small></div></div></div></div></section>
<section className="section" id="jobs" style={{paddingTop:12}}><div className="container"><div className="section-head"><div><h2>Latest government jobs</h2><p>{jobs.length ? `Showing ${jobs.length} active published jobs from the portal database.` : "Browse published listings and review their official sources."}</p></div><a className="link" href="/jobs">Browse all jobs <ArrowRight size={14} style={{display:"inline",verticalAlign:"middle"}}/></a></div>{jobs.length ? <div className="job-grid">{jobs.map(job=><JobCard key={job.id} job={job}/>)}</div> : <div className="empty-state">No published job listings are available yet. New listings appear after source review.</div>}</div></section>
<section className="section" id="exams"><div className="container"><div className="section-head"><div><h2>Exam calendar & upcoming exams</h2><p>Published exam records and their recorded milestones.</p></div><a className="link" href="/exams">View all exams <ArrowRight size={14} style={{display:"inline",verticalAlign:"middle"}}/></a></div>{exams.length ? <div className="category-grid">{exams.slice(0,12).map(exam => <a className="category" href={`/exams/${exam.slug}`} key={exam.id}><span><b>{exam.name}</b><small style={{display:"block",marginTop:4,color:"#64758b"}}>{exam.organization}</small></span><ChevronRight size={16} style={{marginLeft:"auto",color:"#8291a3"}}/></a>)}</div> : <div className="empty-state">No exam records have been published yet.</div>}</div></section>
<section className="section" id="eligibility"><div className="container"><div className="banner"><div><h3>Know where you stand before you apply.</h3><p>Add your education, age, category and location to check recorded job criteria. Unclear conditions are flagged for manual review.</p></div><a href="/eligibility" className="btn btn-primary">Check eligibility <ArrowRight size={15}/></a></div></div></section>
<section className="section" id="exams"><div className="container"><div className="section-head"><div><h2>Browse by department</h2><p>Explore central and state opportunities by the fields you care about.</p></div><a className="link" href="/search">Search listings <ArrowRight size={14} style={{display:"inline",verticalAlign:"middle"}}/></a></div><div className="category-grid">{categories.map(c=><a className="category" href={`/search?department=${encodeURIComponent(c.name)}`} key={c.name}><span className="category-icon">{c.icon}</span>{c.name}<ChevronRight size={16} style={{marginLeft:"auto",color:"#8291a3"}}/></a>)}</div></div></section>
<section className="section" id="updates"><div className="container two-col">
  <div><div className="section-head"><div><h2>Latest updates</h2><p>Published results, admit cards, and answer keys.</p></div><a className="link" href="/results">All results</a></div><div className="update-card">{updates.length ? updates.map(update => (
    <a className="update-row" key={update.id} href={`/${update.type === "ADMIT_CARD" ? "admit-card" : update.type === "ANSWER_KEY" ? "answer-key" : "results"}/${update.job.slug}`}>
      <div><b>{update.title}</b><small>{update.sourceOrganization ?? update.job.organization}</small></div><span className="status">{update.type.replaceAll("_", " ")}</span>
    </a>
  )) : <div className="empty-state">No result or admit-card updates have been published yet.</div>}</div></div>
  <div><div className="section-head"><div><h2>Your prep, in one place</h2><p>Follow exams and keep preparation organized.</p></div></div><div className="update-card">
    <a className="update-row" href="/preparation"><div><b><BookOpen size={15} style={{display:"inline",verticalAlign:"middle"}}/> Followed exam plans</b><small>Recorded milestones and verified resources</small></div><ChevronRight size={16}/></a>
    <a className="update-row" href="/previous-papers"><div><b><TrendingUp size={15} style={{display:"inline",verticalAlign:"middle"}}/> Previous papers</b><small>Browse only when source-backed papers are available</small></div><ChevronRight size={16}/></a>
    <a className="update-row" href="/exams"><div><b><Users size={15} style={{display:"inline",verticalAlign:"middle"}}/> Browse and follow exams</b><small>Keep recorded dates together</small></div><ChevronRight size={16}/></a>
  </div></div>
</div></section>
<footer className="footer"><div className="container footer-in"><div><Brand/><p style={{maxWidth:360,lineHeight:1.6,fontSize:13}}>A clearer way to find government opportunities that may fit your profile.</p><small>Official recruitment information belongs to its issuing organization. Always verify details in the original notice.</small></div><div><b>Explore</b><p><small>Latest Jobs · Results · Admit Cards · Exam Calendar</small></p></div><div><b>About NaukriMitra</b><p><small>About · Contact · Privacy · Terms · Disclaimer</small></p></div></div></footer></main>}
