import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, ExternalLink, ShieldCheck } from "lucide-react";
import { FollowExamButton } from "../../follow-exam-button";

const API = process.env.API_URL ?? "http://localhost:4000";
type Exam = { id: string; slug: string; name: string; organization: string; overview: string | null; officialUrl: string | null; sourceKind: string; events: { id: string; type: string; date: string | null; endDate: string | null; title: string | null; officialUrl: string | null; sourceKind: string }[] };
async function getExam(slug: string): Promise<Exam | null> { try { const response = await fetch(`${API}/api/v1/exams/${encodeURIComponent(slug)}`, { next: { revalidate: 60 } }); return response.ok ? (await response.json()).data : null; } catch { return null; } }
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "long" }).format(new Date(value)) : "Date not recorded";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const exam = await getExam(slug); return exam ? { title: `${exam.name} — Exam details`, description: `${exam.name} dates and source details. Review the issuing organization's official page.`, alternates: { canonical: `/exams/${exam.slug}` }, openGraph: { title: exam.name, description: `Exam dates and source details for ${exam.name}.`, type: "article" } } : { title: "Exam not found" }; }
export default async function ExamDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const exam = await getExam(slug); if (!exam) notFound();
  return <main><header className="header"><div className="container header-in"><a className="brand" href="/"><span className="brand-mark">N</span><span>Naukri<span style={{ color: "#087b69" }}>Setu</span></span></a><a className="btn btn-light" href="/preparation">Preparation <span aria-hidden="true">→</span></a></div></header><section className="listing-page"><div className="container exam-detail"><a className="link" href="/exams"><ArrowLeft size={14}/> All exams</a><span className={exam.sourceKind === "OFFICIAL" ? "pill" : "status"}>{exam.sourceKind === "OFFICIAL" ? <><ShieldCheck size={13}/> Official exam source</> : `${exam.sourceKind} information`}</span><h1>{exam.name}</h1><p>{exam.organization}</p>{exam.overview && <p>{exam.overview}</p>}<div className="exam-actions">{exam.officialUrl && <a className="btn btn-light" href={exam.officialUrl} target="_blank" rel="noreferrer">Official exam page <ExternalLink size={14}/></a>}<FollowExamButton examId={exam.id}/></div><h2>Recorded exam milestones</h2>{exam.events.length === 0 ? <div className="empty-state">No exam dates have been recorded. Do not rely on unofficial estimates.</div> : <div className="calendar-list">{exam.events.map(event=><article className="update-card calendar-event" key={event.id}><div className="calendar-date"><CalendarDays size={17}/><b>{date(event.date)}</b></div><div><span className="tag">{event.type.replaceAll("_", " ")}</span><h2>{event.title ?? exam.name}</h2>{event.endDate && <p>Through {date(event.endDate)}</p>}<p>Source type: {event.sourceKind}</p></div>{(event.officialUrl ?? exam.officialUrl) && <a className="link" href={event.officialUrl ?? exam.officialUrl!} target="_blank" rel="noreferrer">Source <ExternalLink size={13}/></a>}</article>)}</div>}</div></section></main>;
}
