import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, ExternalLink, ShieldCheck } from "lucide-react";

type ContentPage = { title: string; description: string; paragraphs: string[]; dataHub?: boolean; legalDraft?: boolean };
const pages: Record<string, ContentPage> = {
  about: { title: "About NaukriSetu", description: "A government-job discovery service focused on profile-based eligibility and clear source information.", paragraphs: ["NaukriSetu helps candidates find public recruitment notices relevant to their profile. It is an independent information service and is not a government agency.", "Recruitment information is shown with its recorded source and verification status. The issuing organization’s original notification remains authoritative."] },
  contact: { title: "Contact", description: "Contact channel for NaukriSetu users.", paragraphs: ["A support contact channel has not been configured for this deployment. Do not use this page to submit sensitive personal documents."] },
  privacy: { title: "Privacy Policy", description: "Draft privacy information for NaukriSetu accounts and candidate profiles.", legalDraft: true, paragraphs: ["This draft describes the data this application is designed to store: account email, password hash, candidate profile fields, saved jobs, application statuses, followed exams, and reminder preferences.", "Passwords are hashed before storage. Refresh tokens are stored as hashes and delivered in HttpOnly cookies. Profile information is used to assess recorded job criteria and should not be treated as a guarantee of eligibility.", "Before public launch, the operator must complete legal review, set a retention schedule, identify processors and hosting regions, and publish a working privacy contact and data-deletion process."] },
  terms: { title: "Terms of Use", description: "Draft terms for use of the NaukriSetu recruitment information service.", legalDraft: true, paragraphs: ["NaukriSetu is an independent service and is not affiliated with any government organization. Users should verify every requirement, date, vacancy, and application link in the issuing organization’s notification.", "Eligibility results are informational checks against criteria recorded in this service. They do not replace an official determination or guarantee acceptance of an application.", "These draft terms require review by qualified counsel and must be adapted to the service operator and applicable law before launch."] },
  disclaimer: { title: "Disclaimer", description: "Important information about recruitment sources and eligibility assessments.", paragraphs: ["NaukriSetu is not a government website. Official recruitment notifications and the issuing organization’s website are the final authority.", "A status of Eligible means only that supplied profile fields match criteria recorded in this listing. If any official condition cannot be checked, the listing should say Check notification. Always review the original notice before applying.", "Source status is shown for each record. An unverified record must not be treated as official information."] },
  "government-schemes": { title: "Government Schemes", description: "Scheme information published only after its source is recorded.", dataHub: true, paragraphs: ["No government scheme records have been entered. This page will remain empty until source-backed information is available."] },
  scholarships: { title: "Scholarships", description: "Scholarship information published only after its source is recorded.", dataHub: true, paragraphs: ["No scholarship records have been entered. Check the relevant official department or institution for current opportunities."] },
  "previous-papers": { title: "Previous Papers and Exam Data", description: "Previous-year papers, cutoffs, vacancies, and exam patterns with source labels.", dataHub: true, paragraphs: ["No previous-paper or historical exam records have been entered yet. We do not publish estimated cutoffs, vacancy counts, or fabricated papers."] },
};
export function generateStaticParams() { return Object.keys(pages).map(slug => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = pages[slug]; return page ? { title: page.title, description: page.description, alternates: { canonical: `/${slug}` }, openGraph: { title: page.title, description: page.description }, ...(page.dataHub || page.legalDraft || slug === "contact" ? { robots: { index: false, follow: true } } : {}) } : { title: "Page not found" }; }
export default async function InformationPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const aliases: Record<string, string> = { "latest-jobs": "/jobs", "government-jobs": "/jobs", "exam-calendar": "/calendar", "saved-jobs": "/dashboard", "application-tracker": "/dashboard", "my-dashboard": "/dashboard" };
  if (aliases[slug]) redirect(aliases[slug]);
  const page = pages[slug]; if (!page) notFound();
  return <main><header className="header"><div className="container header-in"><a className="brand" href="/"><span className="brand-mark">N</span><span>Naukri<span style={{ color: "#087b69" }}>Setu</span></span></a><a className="btn btn-light" href="/"><ArrowLeft size={14}/> Home</a></div></header><section className="listing-page"><div className="container info-page"><a className="link" href="/"><ArrowLeft size={14}/> Home</a><h1>{page.title}</h1><p>{page.description}</p>{page.legalDraft && <p className="status legal-draft">Draft policy · Requires legal review before launch</p>}{page.dataHub && <div className="source-box"><ShieldCheck size={16}/> Content is published only when a source record is available.</div>}<div className="info-copy">{page.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div>{slug === "contact" && process.env.NEXT_PUBLIC_SUPPORT_EMAIL && <a className="btn btn-primary" href={`mailto:${process.env.NEXT_PUBLIC_SUPPORT_EMAIL}`}>Email support <ExternalLink size={14}/></a>}</div></section></main>;
}
